var listaDeLeitura = [{ id: "1", capa: "https://pbs.twimg.com/media/ESLeoC0XsAAqI1N.jpg", nome: "Amor Doce", link: "https://www.spiritfanfiction.com/listas/amor-doce-7929400", },
    { id: "2", capa: "https://images.alphacoders.com/639/639788.jpg", nome: "Another", link: "https://www.spiritfanfiction.com/listas/another-7929401", },
    { id: "3", capa: "https://1.bp.blogspot.com/-Gi3PAOksJpI/YDcAVyYrUXI/AAAAAAAC_7E/lEyx3n1ggzsOlzai6L1rb7c106DXbm5PgCLcBGAsYHQ/w1200-h630-p-k-no-nu/avatar-novofilme-mestredoar-lendades.jpg", nome: "Avatar - A Lenda de Aang", link: "https://www.spiritfanfiction.com/listas/avatar-a-lenda-de-aang-7932915", },
    { id: "4", capa: "http://toshiwayume.com.br/wp-content/uploads/2016/03/ballroom-e-youkoso-6498427.jpg", nome: "Ballroom e Youkoso", link: "https://www.spiritfanfiction.com/listas/ballroom-e-youkuso-7932916", },
    { id: "5", capa: "https://www.corsan.com.br/themes/padrao2019/images/outros/GD_imgSemImagem.png", nome: "Beauty and the Beasts", link: "https://www.spiritfanfiction.com/listas/beauty-and-the-beasts-7932918", },
    { id: "6", capa: "https://rollingstone.uol.com.br/media/_versions/big-time-rush-gettyimages-126288545_widelg.jpg", nome: "Big Time Rush", link: "https://www.spiritfanfiction.com/listas/big-time-rush-7932920", },
    { id: "7", capa: "https://areajugones.sport.es/wp-content/uploads/2021/03/imagen-2021-03-31-094042-1080x609.jpg", nome: "Black Clover", link: "https://www.spiritfanfiction.com/listas/black-clover-7932923", },
    { id: "8", capa: "https://www.planocritico.com/wp-content/uploads/2017/09/78-My-Hero-Academia-1-Temporada.jpg", nome: "Boku no Hero Academia", link: "https://www.spiritfanfiction.com/listas/boku-no-hero-academia-7932931", },
    { id: "9", capa: "https://www.jbox.com.br/wp/wp-content/uploads/2018/07/bungostraydogs-destacada.jpg", nome: "Bungou Stray Dogs", link: "https://www.spiritfanfiction.com/listas/bungou-stray-dogs-7932944", },
    { id: "10", capa: "https://cdn.ome.lt/k9Zr8E0Sb2bbHMCPUmHYVGExsqM=/1200x630/smart/extras/conteudos/burn-the-witch-manga.jpg", nome: "Burn the Witch", link: "https://www.spiritfanfiction.com/listas/burn-the-witch-7932948", },
    { id: "11", capa: "https://farm1.staticflickr.com/799/40909731121_1e704c9fd1_b.jpg", nome: "B: the Beginning", link: "https://www.spiritfanfiction.com/listas/b-the-beginning-7932952", },
    { id: "12", capa: "https://ramenparados.com/wp-content/uploads/2018/09/Castlevania-900x600.jpg", nome: "Castlevania", link: "https://www.spiritfanfiction.com/listas/castlevania-7932953", },
    { id: "13", capa: "https://jornaldaparaiba.com.br/wp-content/uploads/2021/12/cobra-kai-temporada-4_dm1d.jpg", nome: "Cobra Kai", link: "https://www.spiritfanfiction.com/listas/cobra-kai-8159371", },
    { id: "14", capa: "https://www.pockettactics.com/wp-content/uploads/2021/01/cookie-run-kingdom-release-date-1200x675.jpg", nome: "Cookie Run: Kingdom", link: "https://www.spiritfanfiction.com/listas/cookie-run-kingdom-8166511", },
    { id: "15", capa: "https://wallpaperaccess.com/full/398513.jpg", nome: "Danganronpa", link: "https://www.spiritfanfiction.com/listas/danganronpa-8166514", },
    { id: "16", capa: "https://uploads.jovemnerd.com.br/wp-content/uploads/2022/02/dc-comics-crise-sombria-1.jpg", nome: "DC", link: "https://www.spiritfanfiction.com/listas/dc-8166516", },
    { id: "17", capa: "https://ptanime.com/wp-content/uploads/2015/04/Analise_Death-Note_Imagem_1.jpg", nome: "Death Note", link: "https://www.spiritfanfiction.com/listas/death-note-8166521", },
    { id: "18", capa: "https://i.pinimg.com/originals/a3/1f/d3/a31fd3d1799c1d34a519a01bc0ef0881.jpg", nome: "Demashitaa Powerpuff Girls Z", link: "https://www.spiritfanfiction.com/listas/demashitaa-powerpuff-girls-z-8166523", },
    { id: "19", capa: "https://images.gnwcdn.com/2018/articles/2018-05-23-12-09/-1527073748272.jpg/EG11/resize/1200x-1/-1527073748272.jpg", nome: "Detroit: Become Human", link: "https://www.spiritfanfiction.com/listas/detroit-become-human-8166795", },
    { id: "20", capa: "https://mangathrill.com/wp-content/uploads/2019/09/drrt.png", nome: "Dr. Stone", link: "https://www.spiritfanfiction.com/listas/dr-stone-8166798", },
    { id: "21", capa: "https://blogs.opovo.com.br/bancadoanime/wp-content/uploads/sites/59/2019/06/fire-force-anime-novo-poster-promocional_trecobox-740x444.jpg", nome: "En En no Shouboutai", link: "https://www.spiritfanfiction.com/listas/en-en-no-shouboutai-8166806", },
    { id: "22", capa: "https://criticalhits.com.br/wp-content/uploads/2021/09/29ef06e70d8a2cefa412ad92b42551af0ab31646r1-1280-720v2_uhq.jpg", nome: "Fairy Tail", link: "https://www.spiritfanfiction.com/listas/fairy-tail-8166810", },
    { id: "23", capa: "https://files.tecnoblog.net/wp-content/uploads/2019/10/fate-grand-order-001.jpg", nome: "Fate/Grand Order", link: "https://www.spiritfanfiction.com/listas/fategrand-order-8166811", },
    { id: "24", capa: "https://images6.alphacoders.com/518/thumb-1920-518865.jpg", nome: "Free", link: "https://www.spiritfanfiction.com/listas/free-8166812", },
    { id: "25", capa: "https://deliriumnerd.com/wp-content/uploads/2020/01/Gakuen-Babysitters-e-a-subvers%C3%A3o-da-masculinidade-t%C3%B3xica.jpg", nome: "Gakuen Babysitters", link: "https://www.spiritfanfiction.com/listas/gakuen-babysitters-8166813", },
    { id: "26", capa: "https://sm.ign.com/ign_br/news/g/genshin-im/genshin-impact-will-add-its-4-remaining-locations-across-the_rj3h.jpg", nome: "Genshin Impact", link: "https://www.spiritfanfiction.com/listas/genshin-impact-8166816", },
    { id: "27", capa: "https://www.comboinfinito.com.br/principal/wp-content/uploads/2019/05/gintama.jpg", nome: "Gintama", link: "https://www.spiritfanfiction.com/listas/gintama-8166821", },
    { id: "28", capa: "https://observatoriodocinema.uol.com.br/wp-content/uploads/2021/01/0_CYzB5LSagBcAxQEM.jpg", nome: "Glee", link: "https://www.spiritfanfiction.com/listas/glee-8166823", },
    { id: "29", capa: "https://sucodemanga.com.br/wp-content/uploads/2020/10/golden-kamuy-suco-apresenta-thumb.jpg", nome: "Golden Kamuy", link: "https://www.spiritfanfiction.com/listas/golden-kamuy-8166824", },
    { id: "30", capa: "https://www.einerd.com.br/wp-content/uploads/2020/08/gravity-falls-e1597152868953.jpeg", nome: "Gravity Falls", link: "https://www.spiritfanfiction.com/listas/gravity-falls-8166826", },
    { id: "31", capa: "https://blogs.opovo.com.br/bancadoanime/wp-content/uploads/sites/59/2017/01/Great-Teacher-Onizuka-photo-de-classe-624x299.jpg", nome: "Great Teacher Onizuka (GTO)", link: "https://www.spiritfanfiction.com/listas/great-teacher-onizuka-gto-8166827", },
    { id: "32", capa: "https://wallpaperaccess.com/full/1991387.jpg", nome: "Haikyuu", link: "https://www.spiritfanfiction.com/listas/haikyuu-8166830", },
    { id: "33", capa: "https://www.whatspaper.com/wp-content/uploads/2021/11/hunter-x-hunter-whatspaper-7.jpg", nome: "Hunter x Hunter", link: "https://www.spiritfanfiction.com/listas/hunter-x-hunter-8166856", },
    { id: "34", capa: "https://d1fz32b7q4znht.cloudfront.net/wp-content/uploads/2020/10/wp4824757-hypnosis-mic-division-rap-battle-wallpapers-1.png", nome: "Hypnosis Mic", link: "https://www.spiritfanfiction.com/listas/hypnosis-mic-8166858", },
    { id: "35", capa: "https://64.media.tumblr.com/b3f6378c011880a8a90c96e983428529/tumblr_p3rma4vjtp1r4uskmo1_1280.jpg", nome: "Ikemen Sengoku", link: "https://www.spiritfanfiction.com/listas/ikemen-sengoku-8166860", },
    { id: "36", capa: "https://wi.wallpapertip.com/wsimgs/21-214998_inazuma-eleven-michiya-kudou.jpg", nome: "Inazuma Eleven", link: "https://www.spiritfanfiction.com/listas/inazuma-eleven-8166862", },
    { id: "37", capa: "https://wallpapercave.com/wp/wp5488476.jpg", nome: "Jibaku Shounen Hanako-kun", link: "https://www.spiritfanfiction.com/listas/jibaku-shounen-hanako-kun-8166863", },
    { id: "38", capa: "https://kanto.legiaodosherois.com.br/w760-h398-gnw-cfill-q95/wp-content/uploads/2021/11/legiao_zsJOGjx7cH2u.png.jpeg", nome: "JoJo's Bizarre Adventure", link: "https://www.spiritfanfiction.com/listas/jojos-bizarre-adventure-8166865", },
    { id: "39", capa: "https://minutootaku.com/wp-content/uploads/2021/05/Review-Jujutsu-Kaisen-mais-do-mesmo-ou-mesmo-do-mais.jpg", nome: "Jujutsu Kaisen", link: "https://www.spiritfanfiction.com/listas/jujutsu-kaisen-8166877", },
    { id: "40", capa: "https://4.bp.blogspot.com/-sCNNIlr8ayU/WudU8skuXbI/AAAAAAAAU1M/Z6-W_-Nw3HIigwIcB__OAthjxeplhT9bwCLcBGAs/s1600/Maid-sama%2Bcop.jpg", nome: "Kaichou wa Maid-sama", link: "https://www.spiritfanfiction.com/listas/kaichou-wa-maid-sama-8166892", },
    { id: "41", capa: "http://images4.fanpop.com/image/photos/21900000/hitman-reborn-katekyo-hitman-reborn-21969059-1024-768.jpg", nome: "Katekyo Hitman Reborn", link: "https://www.spiritfanfiction.com/listas/katekyo-hitman-reborn-8166895", },
    { id: "42", capa: "https://crowfansub.files.wordpress.com/2019/07/5.png", nome: "Kaze ga Tsuyoku Fuiteiru", link: "https://www.spiritfanfiction.com/listas/kaze-ga-tsuyoku-fuiteiru-8166898", },
    { id: "43", capa: "https://sm.ign.com/ign_br/screenshot/default/kimetsu-no-yaiba_jc8q.jpg", nome: "Kimetsu no Yaiba", link: "https://www.spiritfanfiction.com/listas/kimetsu-no-yaiba-8166899", },
    { id: "44", capa: "https://www.theanimedaily.com/wp-content/uploads/2020/10/Kiznaiver-1-e1602935660761.jpg", nome: "Kiznaiver", link: "https://www.spiritfanfiction.com/listas/kiznaiver-8166903", },
    {
        id: "45",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "46",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "47",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "48",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "49",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "50",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "51",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "52",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "53",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "54",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "55",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "56",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "57",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "58",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "59",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "60",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "61",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "62",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "63",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "64",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "65",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "66",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "67",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "68",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "69",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "70",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "71",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "72",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "73",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "74",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "75",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "76",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "77",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "78",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "79",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "80",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "81",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "82",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "83",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "84",
        capa: "",
        nome: "",
        link: "",
    },
    {
        id: "85",
        capa: "",
        nome: "",
        link: "",
    },
]

var elementoExibirListasDeLeitura = document.getElementById("exibirListasDeLeitura");

function ListarListasDeLeitura() {
    elementoExibirListasDeLeitura.innerHTML = "";
    for (var i = 0; i < listaDeLeitura.length; i++) {
        elementoExibirListasDeLeitura.innerHTML =
            elementoExibirListasDeLeitura.innerHTML +
            '<figure><a href="' + listaDeLeitura[i].link + '"><img class="img-listasDeLeitura" src="' + listaDeLeitura[i].capa + '"></a><figcaption>' + listaDeLeitura[i].nome + '</figcaption></figure>';
    }
}

ListarListasDeLeitura();

/*
{
        id: "",
        capa: "",
        nome: "",
        link: "",
    },
*/